

name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
 
jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t rivelino86/portfolio .

      
      - name: Push image
        run: |
             docker lodin -u rivelino86 -p ${{secret.REGISTRY_PASS}}
             docker push rivelino86/portfolio
